import React, { useState, useRef } from "react";
import { jsPDF } from "jspdf";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

import Input from "../Input";
import Button from "../Button";
import { Icons } from "../../constant/icons";

export default function InvoiceForm({ file, data, setData }) {
  const [activeTab, setActiveTab] = useState("edit");
  const [exporting, setExporting] = useState(null);
  const [successMsg, setSuccessMsg] = useState(null);
  const formRef = useRef(null);

  const [isEditing, setIsEditing] = useState(false);

  const handleChange = (e) => {
    setData({ ...data, [e.target.name]: e.target.value });
  };

  const showSuccess = (msg) => {
    setSuccessMsg(msg);
    setTimeout(() => setSuccessMsg(null), 3000);
  };

  const handleSave = async () => {
    try {
      const response = await fetch(`http://localhost:5000/api/invoices/${data._id}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(data),
      });

      if (!response.ok) {
        throw new Error("Failed to save changes on server");
      }

      const updated = await response.json();
      setData(updated);
      setIsEditing(false);
      showSuccess("Changes saved successfully!");
    } catch (err) {
      console.error("Save error:", err);
      alert("Error saving changes: " + err.message);
    }
  };

  // ===== EXPORT PDF =====
  const exportPDF = async () => {
    setExporting("pdf");
    try {
      await new Promise((r) => setTimeout(r, 300));
      const doc = new jsPDF();
      const pw = doc.internal.pageSize.getWidth();

      // Brand band
      doc.setFillColor(79, 70, 229);
      doc.rect(0, 0, pw, 28, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("INVOICE MANAGEMENT SYSTEM", 14, 18);

      // Title
      doc.setTextColor(79, 70, 229);
      doc.setFontSize(26);
      doc.setFont("helvetica", "bold");
      doc.text("INVOICE", 14, 50);

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      doc.text(`Invoice #${data.invoiceNumber}`, 14, 58);
      doc.text(`Date: ${data.invoiceDate}`, 14, 64);

      // Bill To
      doc.setFont("helvetica", "bold");
      doc.setTextColor(50);
      doc.text("Bill To:", 14, 76);
      doc.setFont("helvetica", "normal");
      doc.text(data.clientName || "—", 14, 84);
      doc.text(data.address || "—", 14, 92, { maxWidth: 80 });

      // Table
      const startY = 110;
      doc.setFillColor(79, 70, 229);
      doc.rect(14, startY - 6, pw - 28, 8, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.text("DESCRIPTION", 18, startY);
      doc.text("AMOUNT", pw - 50, startY, { align: "right" });

      doc.setTextColor(60, 60, 60);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);

      const rows = [
        { label: "Taxable Value", value: data.taxableValue },
        { label: "Invoice Value (Total)", value: data.invoiceValue },
      ];

      let rowY = startY + 10;
      rows.forEach((row, i) => {
        if (i % 2 === 0) {
          doc.setFillColor(245, 247, 250);
          doc.rect(14, rowY - 5, pw - 28, 12, "F");
        }
        doc.text(row.label, 18, rowY);
        doc.text(
          `₹ ${Number(row.value).toLocaleString("en-IN")}`,
          pw - 50,
          rowY,
          {
            align: "right",
          },
        );
        rowY += 12;
      });

      // Total
      doc.setDrawColor(79, 70, 229);
      doc.setLineWidth(0.8);
      doc.line(14, rowY, pw - 14, rowY);
      rowY += 8;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(79, 70, 229);
      doc.text("TOTAL:", pw - 100, rowY);
      doc.text(
        `₹ ${Number(data.invoiceValue).toLocaleString("en-IN")}`,
        pw - 14,
        rowY,
        {
          align: "right",
        },
      );

      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(160);
      doc.text("Thank you for your business!", 14, 280);
      doc.text("Generated by Invoice Management System", 14, 286);

      doc.save("invoice.pdf");
      showSuccess("PDF exported successfully!");
    } catch (err) {
      console.error("PDF error:", err);
    }
    setExporting(null);
  };

  // ===== EXPORT EXCEL =====
  const exportExcel = async () => {
    setExporting("excel");
    try {
      await new Promise((r) => setTimeout(r, 200));
      const exportData = [
        { Field: "Invoice Number", Value: data.invoiceNumber },
        { Field: "Invoice Date", Value: data.invoiceDate },
        { Field: "Client Name", Value: data.clientName },
        { Field: "Taxable Value", Value: data.taxableValue },
        { Field: "Invoice Value (Total)", Value: data.invoiceValue },
        { Field: "Address", Value: data.address },
      ];
      const ws = XLSX.utils.json_to_sheet(exportData);
      ws["!cols"] = [{ wch: 25 }, { wch: 30 }];
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "Invoice");
      const excelBuffer = XLSX.write(wb, { bookType: "xlsx", type: "array" });
      const blob = new Blob([excelBuffer], {
        type: "application/octet-stream",
      });
      saveAs(blob, "invoice.xlsx");
      showSuccess("Excel exported successfully!");
    } catch (err) {
      console.error("Excel error:", err);
    }
    setExporting(null);
  };

  // ===== EXPORT XML =====
  const exportXML = async () => {
    setExporting("xml");
    try {
      await new Promise((r) => setTimeout(r, 200));
      const xml = `<?xml version="1.0" encoding="UTF-8"?>
<TALLYMESSAGE>
  <INVOICE>
    <NUMBER>${data.invoiceNumber}</NUMBER>
    <DATE>${data.invoiceDate}</DATE>
    <CLIENT>${data.clientName}</CLIENT>
    <TAXABLE>${data.taxableValue}</TAXABLE>
    <TOTAL>${data.invoiceValue}</TOTAL>
    <ADDRESS>${data.address}</ADDRESS>
  </INVOICE>
</TALLYMESSAGE>`;
      const blob = new Blob([xml], { type: "text/xml" });
      saveAs(blob, "invoice.xml");
      showSuccess("XML exported successfully!");
    } catch (err) {
      console.error("XML error:", err);
    }
    setExporting(null);
  };

  const previewUrl = file ? URL.createObjectURL(file) : data?.fileUrl;
  const isPdf = file
    ? file.type === "application/pdf"
    : (data?.fileUrl?.toLowerCase().endsWith(".pdf") || data?.filePath?.toLowerCase().endsWith(".pdf"));

  return (
    <div className="relative pb-10">
      {/* Success Toast */}
      {successMsg && (
        <div className="fixed top-20 right-6 z-50 animate-fade-in-right">
          <div className="flex items-center gap-3 bg-white border border-emerald-200 text-emerald-800 px-5 py-3.5 rounded-2xl shadow-xl shadow-emerald-200/30">
            <div className="w-7 h-7 rounded-full bg-emerald-100 flex items-center justify-center flex-shrink-0">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.5"
                strokeLinecap="round"
                strokeLinejoin="round"
                className="text-emerald-600"
              >
                <polyline points="20 6 9 17 4 12" />
              </svg>
            </div>
            <span className="text-sm font-semibold">{successMsg}</span>
            <button
              onClick={() => setSuccessMsg(null)}
              className="ml-1 p-1 rounded-lg hover:bg-gray-100 transition-colors text-gray-400 hover:text-gray-600"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="14"
                height="14"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.5"
                strokeLinecap="round"
                strokeLinejoin="round"
              >
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>
          </div>
        </div>
      )}

      <div className="max-w-6xl mx-auto px-4 sm:px-6 pt-6 space-y-5">
        {/* ===== PAGE HEADER ===== */}
        <div className="animate-fade-in-down">
          <div className="bg-white rounded-2xl shadow-lg shadow-gray-200/50 border border-gray-100 p-5 sm:p-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="flex items-center gap-4">
                <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-indigo-100 to-blue-100 border border-indigo-200 flex items-center justify-center text-indigo-600">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="22"
                    height="22"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M14 3v4a1 1 0 0 0 1 1h4" />
                    <path d="M17 21H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7l5 5v11a2 2 0 0 1-2 2z" />
                  </svg>
                </div>
                <div>
                  <h2 className="text-lg sm:text-xl font-bold text-gray-900">
                    Invoice Editor
                  </h2>
                  <p className="text-sm text-gray-500 mt-0.5">
                    Edit invoice details and export in multiple formats
                  </p>
                </div>
              </div>

              {/* Status badges */}
              <div className="flex items-center gap-2">
                <div className="flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-amber-50 border border-amber-100">
                  <span className="w-1.5 h-1.5 rounded-full bg-amber-500 animate-pulse" />
                  <span className="text-xs font-semibold text-amber-700">
                    Draft
                  </span>
                </div>
                <div className="px-3 py-1.5 rounded-full bg-gray-50 border border-gray-200 text-xs font-semibold text-gray-600">
                  {data?.invoiceNumber || "INV-001"}
                </div>
              </div>
            </div>

            {/* Tab switcher */}
            <div className="mt-5 flex items-center gap-1 p-1 bg-gray-100 rounded-xl w-fit">
              {[
                { key: "edit", label: "Edit", icon: "edit" },
                { key: "preview", label: "Preview", icon: "preview" },
              ].map((tab) => (
                <button
                  key={tab.key}
                  onClick={() => setActiveTab(tab.key)}
                  className={`flex items-center gap-1.5 px-4 py-2 rounded-lg text-xs font-semibold transition-all duration-200 ${
                    activeTab === tab.key
                      ? "bg-white text-indigo-700 shadow-sm"
                      : "text-gray-500 hover:text-gray-700"
                  }`}
                >
                  {tab.key === "edit" ? (
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="14"
                      height="14"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                      <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                    </svg>
                  ) : (
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="14"
                      height="14"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2.5"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
                      <circle cx="12" cy="12" r="3" />
                    </svg>
                  )}
                  {tab.label}
                </button>
              ))}
            </div>
          </div>
        </div>

        {/* ===== PREVIEW TAB ===== */}
        {activeTab === "preview" && (
          <div className="animate-fade-in-up">
            {/* Live preview card */}
            <div className="bg-white rounded-2xl shadow-lg shadow-gray-200/50 border border-gray-100 overflow-hidden">
              <div className="p-6 sm:p-8 max-w-[650px] mx-auto">
                {/* Invoice header */}
                <div className="flex justify-between items-start border-b-2 border-indigo-200 pb-6">
                  <div>
                    <p className="text-xs font-semibold text-gray-400 uppercase tracking-[0.15em]">
                      Company
                    </p>
                    <p className="text-lg font-extrabold text-gray-900 mt-1">
                      Invoice Management System
                    </p>
                    <p className="text-sm text-gray-400 mt-0.5">
                      123 Business Street, Financial District
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs font-semibold text-indigo-600 uppercase tracking-[0.15em]">
                      Invoice
                    </p>
                    <p className="text-2xl font-extrabold text-gray-900 mt-1">
                      #{data?.invoiceNumber || "INV-001"}
                    </p>
                  </div>
                </div>

                {/* Info grid */}
                <div className="grid grid-cols-2 gap-8 py-6">
                  <div>
                    <p className="text-xs font-semibold text-gray-400 uppercase tracking-[0.15em]">
                      Bill To
                    </p>
                    <p className="text-base font-bold text-gray-900 mt-1.5">
                      {data?.clientName || "Client Name"}
                    </p>
                    <p className="text-sm text-gray-500 mt-0.5 leading-relaxed">
                      {data?.address || "Address"}
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="text-xs font-semibold text-gray-400 uppercase tracking-[0.15em]">
                      Date
                    </p>
                    <p className="text-base font-bold text-gray-900 mt-1.5">
                      {data?.invoiceDate || "—"}
                    </p>
                    <p className="text-xs text-gray-400 mt-2">
                      Payment Due: Upon Receipt
                    </p>
                  </div>
                </div>

                {/* Table */}
                <table className="w-full border-collapse">
                  <thead>
                    <tr>
                      <th className="text-left text-[11px] font-bold text-white uppercase tracking-wider py-3 px-4 bg-indigo-600 rounded-tl-xl">
                        Description
                      </th>
                      <th className="text-right text-[11px] font-bold text-white uppercase tracking-wider py-3 px-4 bg-indigo-600 rounded-tr-xl">
                        Amount (₹)
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b border-gray-100">
                      <td className="py-4 px-4 text-sm text-gray-700 font-medium">
                        Taxable Value
                      </td>
                      <td className="py-4 px-4 text-right text-sm text-gray-900 font-bold">
                        {Number(data?.taxableValue || 0).toLocaleString(
                          "en-IN",
                        )}
                      </td>
                    </tr>
                    <tr>
                      <td className="py-4 px-4 text-sm text-gray-700 font-medium">
                        Invoice Value (Total)
                      </td>
                      <td className="py-4 px-4 text-right text-sm text-gray-900 font-bold">
                        {Number(data?.invoiceValue || 0).toLocaleString(
                          "en-IN",
                        )}
                      </td>
                    </tr>
                  </tbody>
                </table>

                {/* Total */}
                <div className="flex justify-end mt-5">
                  <div className="w-56 bg-gradient-to-br from-indigo-600 to-blue-700 rounded-2xl p-5">
                    <p className="text-xs text-indigo-200 font-semibold uppercase tracking-wider">
                      Total Amount
                    </p>
                    <p className="text-2xl font-extrabold text-white mt-1">
                      ₹{" "}
                      {Number(data?.invoiceValue || 0).toLocaleString("en-IN")}
                    </p>
                  </div>
                </div>

                {/* Footer */}
                <div className="mt-6 pt-5 border-t border-gray-100 text-center">
                  <p className="text-xs text-gray-400">
                    Thank you for your business!
                  </p>
                </div>
              </div>
            </div>

            {/* Export buttons */}
            <div className="flex flex-wrap items-center gap-3 mt-5">
              <Button
                variant="primary"
                onClick={exportPDF}
                iconLeft={Icons.pdf}
                loading={exporting === "pdf"}
              >
                Export PDF
              </Button>
              <Button
                variant="success"
                onClick={exportExcel}
                iconLeft={Icons.excel}
                loading={exporting === "excel"}
              >
                Export Excel
              </Button>
              <Button
                variant="warning"
                onClick={exportXML}
                iconLeft={Icons.xml}
                loading={exporting === "xml"}
              >
                Export XML
              </Button>
              <Button
                variant="outline"
                onClick={() => window.print()}
                iconLeft={Icons.print}
              >
                Print
              </Button>
            </div>
          </div>
        )}

        {/* ===== EDIT TAB ===== */}
        {activeTab === "edit" && (
          <div className="animate-fade-in-up">
            <div className="grid grid-cols-1 lg:grid-cols-5 gap-5">
              {/* LEFT - Upload Preview */}
              <div className="lg:col-span-2">
                <div className="bg-white rounded-2xl shadow-lg shadow-gray-200/50 border border-gray-100 overflow-hidden h-full flex flex-col">
                  <div className="p-4 border-b border-gray-100 flex items-center gap-3">
                    <div className="w-8 h-8 rounded-lg bg-indigo-100 flex items-center justify-center text-indigo-600">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="16"
                        height="16"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z" />
                        <circle cx="12" cy="12" r="3" />
                      </svg>
                    </div>
                    <div>
                      <p className="text-sm font-bold text-gray-900">
                        Original Upload
                      </p>
                      <p className="text-xs text-gray-400">Reference image</p>
                    </div>
                  </div>
                  <div className="p-4 flex-1 flex items-center justify-center">
                    {previewUrl ? (
                      <div className="relative group w-full">
                        {isPdf ? (
                          <iframe
                            src={previewUrl}
                            title="Invoice Reference"
                            className="w-full h-72 rounded-xl border border-gray-200"
                          />
                        ) : (
                          <img
                            src={previewUrl}
                            alt="invoice"
                            className="w-full h-72 object-contain rounded-xl border border-gray-200 bg-gray-50/50"
                          />
                        )}
                      </div>
                    ) : (
                      <div className="w-full h-72 rounded-xl border-2 border-dashed border-gray-200 bg-gray-50/30 flex flex-col items-center justify-center gap-3 text-gray-400">
                        <svg
                          xmlns="http://www.w3.org/2000/svg"
                          width="36"
                          height="36"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <rect
                            x="3"
                            y="3"
                            width="18"
                            height="18"
                            rx="2"
                            ry="2"
                          />
                          <circle cx="8.5" cy="8.5" r="1.5" />
                          <polyline points="21 15 16 10 5 21" />
                        </svg>
                        <p className="text-sm font-semibold">
                          No file uploaded
                        </p>
                        <p className="text-xs text-gray-400">
                          Upload a bill image for reference
                        </p>
                      </div>
                    )}
                  </div>
                </div>
              </div>

              {/* RIGHT - Form */}
              <div className="lg:col-span-3">
                <div
                  ref={formRef}
                  className="bg-white rounded-2xl shadow-lg shadow-gray-200/50 border border-gray-100 overflow-hidden"
                >
                  {/* Form Header */}
                  <div className="p-5 bg-gradient-to-r from-indigo-600 to-blue-700 relative overflow-hidden">
                    <div className="absolute -top-10 -right-10 w-40 h-40 bg-white/5 rounded-full blur-2xl" />
                    <div className="absolute -bottom-10 -left-10 w-32 h-32 bg-white/5 rounded-full blur-2xl" />
                    <div className="relative flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <div className="w-9 h-9 rounded-xl bg-white/10 flex items-center justify-center">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="18"
                            height="18"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="white"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          >
                            <rect
                              x="4"
                              y="2"
                              width="16"
                              height="20"
                              rx="2"
                              ry="2"
                            />
                            <path d="M9 22v-4h6v4" />
                            <line x1="8" y1="6" x2="10" y2="6" />
                            <line x1="14" y1="6" x2="16" y2="6" />
                          </svg>
                        </div>
                        <div>
                          <p className="text-xs text-white/70 font-semibold uppercase tracking-wider">
                            Company
                          </p>
                          <p className="text-base font-extrabold text-white">
                            Invoice Management System
                          </p>
                        </div>
                      </div>
                      <div className="text-right">
                        <p className="text-xs text-white/70 font-semibold uppercase tracking-wider">
                          Invoice
                        </p>
                        <p className="text-xl font-extrabold text-white">
                          #{data?.invoiceNumber || "INV-001"}
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Form Body */}
                  <div className="p-5 space-y-5">
                    {/* Row 1 */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <Input
                        label="Invoice Number"
                        name="invoiceNumber"
                        value={data.invoiceNumber}
                        onChange={handleChange}
                        placeholder="INV-2026-001"
                        icon={Icons.hash}
                        disabled={!isEditing}
                      />
                      <Input
                        label="Invoice Date"
                        name="invoiceDate"
                        type="date"
                        value={data.invoiceDate}
                        onChange={handleChange}
                        placeholder="YYYY-MM-DD"
                        icon={Icons.calendar}
                        disabled={!isEditing}
                      />
                    </div>

                    {/* Row 2 */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <Input
                        label="Client Name"
                        name="clientName"
                        value={data.clientName}
                        onChange={handleChange}
                        placeholder="ABC Pvt Ltd"
                        icon={Icons.user}
                        disabled={!isEditing}
                      />
                      <Input
                        label="Taxable Value"
                        name="taxableValue"
                        type="number"
                        value={data.taxableValue}
                        onChange={handleChange}
                        placeholder="50000"
                        icon={Icons.dollar}
                        disabled={!isEditing}
                      />
                    </div>

                    {/* Row 3 */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <Input
                        label="Invoice Value (Total)"
                        name="invoiceValue"
                        type="number"
                        value={data.invoiceValue}
                        onChange={handleChange}
                        placeholder="59000"
                        icon={Icons.rupee}
                        disabled={!isEditing}
                      />
                      <div className="rounded-xl border-2 border-indigo-100 bg-gradient-to-br from-indigo-50 to-blue-50/30 p-4 flex flex-col justify-center">
                        <div className="flex items-center gap-2 text-indigo-600">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="16"
                            height="16"
                            viewBox="0 0 24 24"
                            fill="none"
                            stroke="currentColor"
                            strokeWidth="2"
                            strokeLinecap="round"
                            strokeLinejoin="round"
                          >
                            <path d="M12 3v2m0 14v2m-7-9H3m18 0h-2M5.64 5.64l1.41 1.41m9.54 9.54l1.41 1.41M5.64 18.36l1.41-1.41m9.54-9.54l1.41-1.41" />
                            <path d="M12 7l.75 1.55L14.5 9.25l-1.75.7L12 11.5l-.75-1.55L9.5 9.25l1.75-.7z" />
                          </svg>
                          <p className="text-xs font-bold uppercase tracking-wider">
                            Quick Notes
                          </p>
                        </div>
                        <p className="text-sm text-indigo-700/70 font-medium mt-2 pl-[22px]">
                          Values update in real-time. Exports use current data.
                        </p>
                      </div>
                    </div>

                    {/* Address + Totals */}
                    <div className="grid grid-cols-1 lg:grid-cols-5 gap-4">
                      <div className="lg:col-span-3">
                        <div className={`relative rounded-xl border-2 border-gray-200 transition-all duration-200 bg-white focus-within:border-indigo-500 focus-within:shadow-sm focus-within:shadow-indigo-100 hover:border-gray-300 ${
                          !isEditing ? "opacity-60 bg-gray-50/30" : ""
                        }`}>
                          <div className="absolute left-3.5 top-3 text-gray-400">
                            {Icons.mapPin}
                          </div>
                          <label className="text-[10px] font-semibold -top-2.5 left-3 bg-white px-1.5 text-indigo-600 absolute tracking-wide">
                            Bill To / Address
                          </label>
                          <textarea
                            name="address"
                            value={data.address}
                            onChange={handleChange}
                            placeholder="Enter full billing address"
                            disabled={!isEditing}
                            className={`w-full min-h-[110px] bg-transparent outline-none px-4 pt-5 pb-3 pl-[46px] text-sm font-medium text-gray-900 placeholder:text-gray-400 border-0 rounded-xl transition-all duration-200 ${
                              !isEditing ? "cursor-not-allowed opacity-60 bg-gray-50/50" : ""
                            }`}
                          />
                        </div>
                      </div>

                      <div className="lg:col-span-2">
                        <div className="rounded-xl border-2 border-gray-200 bg-white p-4 h-full flex flex-col justify-center">
                          <p className="text-sm font-extrabold text-gray-900 flex items-center gap-2">
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              width="16"
                              height="16"
                              viewBox="0 0 24 24"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2.5"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              className="text-indigo-600"
                            >
                              <line x1="12" y1="1" x2="12" y2="23" />
                              <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
                            </svg>
                            Totals
                          </p>
                          <div className="mt-3 space-y-2">
                            <div className="flex items-center justify-between text-sm">
                              <span className="text-gray-500">
                                Taxable Value
                              </span>
                              <span className="text-gray-900 font-bold">
                                ₹{" "}
                                {Number(data?.taxableValue || 0).toLocaleString(
                                  "en-IN",
                                )}
                              </span>
                            </div>
                            <div className="flex items-center justify-between text-sm">
                              <span className="text-gray-500">
                                Invoice Total
                              </span>
                              <span className="text-gray-900 font-bold">
                                ₹{" "}
                                {Number(data?.invoiceValue || 0).toLocaleString(
                                  "en-IN",
                                )}
                              </span>
                            </div>
                            <div className="h-px bg-gray-100 my-2" />
                            <div className="flex items-center justify-between">
                              <span className="text-gray-900 font-extrabold text-sm">
                                Payable
                              </span>
                              <span className="bg-gradient-to-r from-indigo-600 to-blue-600 bg-clip-text text-transparent font-extrabold text-lg">
                                ₹{" "}
                                {Number(data?.invoiceValue || 0).toLocaleString(
                                  "en-IN",
                                )}
                              </span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Buttons */}
                    <div className="flex flex-wrap items-center gap-3 pt-2 border-t border-gray-100">
                      {isEditing ? (
                        <Button
                          variant="success"
                          onClick={handleSave}
                          iconLeft={
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              width="16"
                              height="16"
                              viewBox="0 0 24 24"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2.5"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            >
                              <polyline points="20 6 9 17 4 12" />
                            </svg>
                          }
                        >
                          Save Changes
                        </Button>
                      ) : (
                        <Button
                          variant="primary"
                          onClick={() => setIsEditing(true)}
                          iconLeft={
                            <svg
                              xmlns="http://www.w3.org/2000/svg"
                              width="16"
                              height="16"
                              viewBox="0 0 24 24"
                              fill="none"
                              stroke="currentColor"
                              strokeWidth="2.5"
                              strokeLinecap="round"
                              strokeLinejoin="round"
                            >
                              <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
                              <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
                            </svg>
                          }
                        >
                          Edit Details
                        </Button>
                      )}

                      <Button
                        variant="primary"
                        onClick={exportPDF}
                        iconLeft={Icons.pdf}
                        loading={exporting === "pdf"}
                        disabled={isEditing}
                      >
                        Export PDF
                      </Button>
                      <Button
                        variant="success"
                        onClick={exportExcel}
                        iconLeft={Icons.excel}
                        loading={exporting === "excel"}
                        disabled={isEditing}
                      >
                        Export Excel
                      </Button>
                      <Button
                        variant="warning"
                        onClick={exportXML}
                        iconLeft={Icons.xml}
                        loading={exporting === "xml"}
                        disabled={isEditing}
                      >
                        Export XML
                      </Button>
                      <Button
                        variant="ghost"
                        onClick={() => {
                          setData({
                            invoiceNumber: "",
                            invoiceDate: "",
                            clientName: "",
                            taxableValue: 0,
                            invoiceValue: 0,
                            address: "",
                          });
                        }}
                        iconLeft={Icons.refresh}
                        disabled={!isEditing}
                      >
                        Reset
                      </Button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
