import React, { useEffect, useMemo, useState } from "react";
import { jsPDF } from "jspdf";
import * as XLSX from "xlsx";
import { saveAs } from "file-saver";

import Button from "../../components/Button";
import { Icons } from "../../constant/icons";

function formatINR(value) {
  const n = Number(value);
  if (Number.isNaN(n)) return "0";
  return n.toLocaleString("en-IN");
}

export default function AllbillPage() {
  const [invoices, setInvoices] = useState([]);
  const [exportingId, setExportingId] = useState(null);
  const [exportingType, setExportingType] = useState(null);
  const [exportingAll, setExportingAll] = useState(null);
  const [refreshing, setRefreshing] = useState(false);

  const fetchInvoices = async () => {
    try {
      const response = await fetch("http://localhost:5000/api/invoices");
      if (!response.ok) {
        throw new Error("Failed to fetch invoices");
      }
      const data = await response.json();
      setInvoices(data);
    } catch (error) {
      console.error("Fetch invoices error:", error);
    }
  };

  useEffect(() => {
    fetchInvoices();
  }, []);

  const refresh = async () => {
    setRefreshing(true);
    try {
      await fetchInvoices();
      // Introduce a tiny delay so the spinner is visible to the user
      await new Promise((resolve) => setTimeout(resolve, 400));
    } finally {
      setRefreshing(false);
    }
  };

  const exportPDF = async (invoice) => {
    if (!invoice) return;

    setExportingId(invoice._id);
    setExportingType("pdf");

    try {
      await new Promise((r) => setTimeout(r, 100));
      const doc = new jsPDF();
      const pw = doc.internal.pageSize.getWidth();
      const ph = doc.internal.pageSize.getHeight();

      // Brand band
      doc.setFillColor(79, 70, 229);
      doc.rect(0, 0, pw, 28, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("INVOICE MANAGEMENT SYSTEM", 14, 18);

      // Title
      doc.setTextColor(79, 70, 229);
      doc.setFontSize(26);
      doc.setFont("helvetica", "bold");
      doc.text("INVOICE", 14, 50);

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      doc.text(`Invoice #${invoice.invoiceNumber}`, 14, 58);
      doc.text(`Date: ${invoice.invoiceDate}`, 14, 64);

      // Bill To
      doc.setFont("helvetica", "bold");
      doc.setTextColor(50);
      doc.text("Bill To:", 14, 76);
      doc.setFont("helvetica", "normal");
      doc.text(invoice.clientName || "—", 14, 84);
      
      // Handle address wrapping safely
      const addressLines = doc.splitTextToSize(invoice.address || "—", 80);
      doc.text(addressLines, 14, 92);

      // Table Y calculation
      const addressHeight = addressLines.length * 5;
      const startY = Math.max(110, 92 + addressHeight + 10);

      doc.setFillColor(79, 70, 229);
      doc.rect(14, startY - 6, pw - 28, 8, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(9);
      doc.text("DESCRIPTION", 18, startY);
      doc.text("AMOUNT", pw - 50, startY, { align: "right" });

      doc.setTextColor(60, 60, 60);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);

      const tableRows = [
        { label: "Taxable Value", value: invoice.taxableValue },
        { label: "Invoice Value (Total)", value: invoice.invoiceValue },
      ];

      let rowY = startY + 10;
      tableRows.forEach((row, i) => {
        if (i % 2 === 0) {
          doc.setFillColor(245, 247, 250);
          doc.rect(14, rowY - 5, pw - 28, 12, "F");
        }
        doc.text(row.label, 18, rowY);
        doc.text(`₹ ${formatINR(row.value)}`, pw - 50, rowY, {
          align: "right",
        });
        rowY += 12;
      });

      // Total
      doc.setDrawColor(79, 70, 229);
      doc.setLineWidth(0.8);
      doc.line(14, rowY, pw - 14, rowY);
      rowY += 8;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(14);
      doc.setTextColor(79, 70, 229);
      doc.text("TOTAL:", pw - 100, rowY);
      doc.text(`₹ ${formatINR(invoice.invoiceValue)}`, pw - 14, rowY, {
        align: "right",
      });

      // Footer
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(160);
      doc.text("Thank you for your business!", 14, ph - 17);
      doc.text("Generated by Invoice Management System", 14, ph - 11);

      doc.save(`invoice-${invoice.invoiceNumber}.pdf`);
    } catch (err) {
      console.error("PDF error:", err);
    }

    setExportingId(null);
    setExportingType(null);
  };

  const exportExcel = async (invoice) => {
    if (!invoice) return;
    setExportingId(invoice._id);
    setExportingType("excel");

    try {
      await new Promise((r) => setTimeout(r, 100));

      const exportData = [
        { Field: "Invoice Number", Value: invoice.invoiceNumber },
        { Field: "Invoice Date", Value: invoice.invoiceDate },
        { Field: "Client Name", Value: invoice.clientName || "—" },
        { Field: "Taxable Value", Value: Number(invoice.taxableValue || 0) },
        { Field: "Invoice Value (Total)", Value: Number(invoice.invoiceValue || 0) },
        { Field: "Address", Value: invoice.address || "—" },
      ];

      const ws = XLSX.utils.json_to_sheet(exportData);
      ws["!cols"] = [{ wch: 25 }, { wch: 30 }];
      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "Invoice");
      const excelBuffer = XLSX.write(wb, { bookType: "xlsx", type: "array" });
      const blob = new Blob([excelBuffer], {
        type: "application/octet-stream",
      });
      saveAs(blob, `invoice-${invoice.invoiceNumber}.xlsx`);
    } catch (err) {
      console.error("Excel error:", err);
    }

    setExportingId(null);
    setExportingType(null);
  };

  const exportXML = async (invoice) => {
    if (!invoice) return;
    setExportingId(invoice._id);
    setExportingType("xml");

    try {
      await new Promise((r) => setTimeout(r, 100));

      const xml = `<?xml version="1.0" encoding="UTF-8"?>
<TALLYMESSAGE>
  <INVOICE>
    <NUMBER>${invoice.invoiceNumber}</NUMBER>
    <DATE>${invoice.invoiceDate}</DATE>
    <CLIENT>${invoice.clientName}</CLIENT>
    <TAXABLE>${invoice.taxableValue}</TAXABLE>
    <TOTAL>${invoice.invoiceValue}</TOTAL>
    <ADDRESS>${invoice.address}</ADDRESS>
  </INVOICE>
</TALLYMESSAGE>`;

      const blob = new Blob([xml], { type: "text/xml" });
      saveAs(blob, `invoice-${invoice.invoiceNumber}.xml`);
    } catch (err) {
      console.error("XML error:", err);
    }

    setExportingId(null);
    setExportingType(null);
  };

  const exportAllPDF = async () => {
    if (!rows.length) return;

    setExportingAll("pdf");
    try {
      await new Promise((r) => setTimeout(r, 50));

      const doc = new jsPDF();
      const pw = doc.internal.pageSize.getWidth();
      const ph = doc.internal.pageSize.getHeight();

      rows.forEach((invoice, idx) => {
        if (idx > 0) {
          doc.addPage();
        }

        // Brand band
        doc.setFillColor(79, 70, 229);
        doc.rect(0, 0, pw, 28, "F");
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(14);
        doc.setFont("helvetica", "bold");
        doc.text("INVOICE MANAGEMENT SYSTEM", 14, 18);

        // Title
        doc.setTextColor(79, 70, 229);
        doc.setFontSize(26);
        doc.setFont("helvetica", "bold");
        doc.text("INVOICE", 14, 50);

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100);
        doc.text(`Invoice #${invoice.invoiceNumber}`, 14, 58);
        doc.text(`Date: ${invoice.invoiceDate}`, 14, 64);

        // Bill To
        doc.setFont("helvetica", "bold");
        doc.setTextColor(50);
        doc.text("Bill To:", 14, 76);
        doc.setFont("helvetica", "normal");
        doc.text(invoice.clientName || "—", 14, 84);
        
        // Wrap address
        const addressLines = doc.splitTextToSize(invoice.address || "—", 80);
        doc.text(addressLines, 14, 92);

        // Table Y calculation
        const addressHeight = addressLines.length * 5;
        const startY = Math.max(110, 92 + addressHeight + 10);

        doc.setFillColor(79, 70, 229);
        doc.rect(14, startY - 6, pw - 28, 8, "F");
        doc.setTextColor(255, 255, 255);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(9);
        doc.text("DESCRIPTION", 18, startY);
        doc.text("AMOUNT", pw - 50, startY, { align: "right" });

        doc.setTextColor(60, 60, 60);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);

        const tableRows = [
          { label: "Taxable Value", value: invoice.taxableValue },
          { label: "Invoice Value (Total)", value: invoice.invoiceValue },
        ];

        let rowY = startY + 10;
        tableRows.forEach((row, i) => {
          if (i % 2 === 0) {
            doc.setFillColor(245, 247, 250);
            doc.rect(14, rowY - 5, pw - 28, 12, "F");
          }
          doc.text(row.label, 18, rowY);
          doc.text(`₹ ${formatINR(row.value)}`, pw - 50, rowY, {
            align: "right",
          });
          rowY += 12;
        });

        // Total
        doc.setDrawColor(79, 70, 229);
        doc.setLineWidth(0.8);
        doc.line(14, rowY, pw - 14, rowY);
        rowY += 8;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(14);
        doc.setTextColor(79, 70, 229);
        doc.text("TOTAL:", pw - 100, rowY);
        doc.text(`₹ ${formatINR(invoice.invoiceValue)}`, pw - 14, rowY, {
          align: "right",
        });

        // Footer
        doc.setFont("helvetica", "normal");
        doc.setFontSize(9);
        doc.setTextColor(160);
        doc.text("Thank you for your business!", 14, ph - 17);
        doc.text("Generated by Invoice Management System", 14, ph - 11);
      });

      doc.save("all-invoices.pdf");
    } catch (err) {
      console.error("Export all PDF error:", err);
    }

    setExportingAll(null);
    setExportingId(null);
    setExportingType(null);
  };

  const exportAllExcel = async () => {
    if (!rows.length) return;

    setExportingAll("excel");
    try {
      await new Promise((r) => setTimeout(r, 50));

      const exportData = rows.map((invoice) => ({
        "Invoice Number": invoice.invoiceNumber,
        "Invoice Date": invoice.invoiceDate,
        "Client Name": invoice.clientName || "—",
        "Taxable Value": Number(invoice.taxableValue || 0),
        "Invoice Value (Total)": Number(invoice.invoiceValue || 0),
        Address: invoice.address || "—",
      }));

      const ws = XLSX.utils.json_to_sheet(exportData);
      ws["!cols"] = [
        { wch: 18 },
        { wch: 15 },
        { wch: 25 },
        { wch: 15 },
        { wch: 20 },
        { wch: 35 },
      ];

      const wb = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(wb, ws, "All Invoices");

      const excelBuffer = XLSX.write(wb, { bookType: "xlsx", type: "array" });
      const blob = new Blob([excelBuffer], {
        type: "application/octet-stream",
      });

      saveAs(blob, "all-invoices.xlsx");
    } catch (err) {
      console.error("Export all Excel error:", err);
    }

    setExportingAll(null);
    setExportingId(null);
    setExportingType(null);
  };

  const rows = useMemo(() => {
    return [...invoices].sort((a, b) => new Date(b?.createdAt || 0) - new Date(a?.createdAt || 0));
  }, [invoices]);

  return (
    <div className="pb-10">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 pt-6 space-y-5">
        <div className="animate-fade-in-down">
          <div className="bg-white rounded-2xl shadow-lg shadow-gray-200/50 border border-gray-100 p-5 sm:p-6">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
              <div className="flex items-center gap-4">
                <div className="w-11 h-11 rounded-xl bg-gradient-to-br from-indigo-100 to-blue-100 border border-indigo-200 flex items-center justify-center text-indigo-600">
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="22"
                    height="22"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="M14 3v4a1 1 0 0 0 1 1h4" />
                    <path d="M17 21H7a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7l5 5v11a2 2 0 0 1-2 2z" />
                    <path d="M9 17h6" />
                    <path d="M9 13h6" />
                    <path d="M9 9h1" />
                  </svg>
                </div>
                <div>
                  <h2 className="text-lg sm:text-xl font-bold text-gray-900">
                    All Bills
                  </h2>
                  <p className="text-sm text-gray-500 mt-0.5">
                    Export PDF / Excel / XML for each saved invoice
                  </p>
                </div>
              </div>

              <div className="flex items-center gap-2 flex-wrap justify-end">
                <Button
                  variant="secondary"
                  onClick={refresh}
                  iconLeft={Icons.refresh}
                  loading={refreshing}
                  disabled={refreshing}
                >
                  Refresh
                </Button>

                <Button
                  variant="primary"
                  onClick={exportAllPDF}
                  iconLeft={Icons.pdf}
                  loading={exportingAll === "pdf"}
                  disabled={rows.length === 0 || exportingAll !== null}
                >
                  Export All PDF
                </Button>

                <Button
                  variant="success"
                  onClick={exportAllExcel}
                  iconLeft={Icons.excel}
                  loading={exportingAll === "excel"}
                  disabled={rows.length === 0 || exportingAll !== null}
                >
                  Export All Excel
                </Button>

                <div className="px-3 py-1.5 rounded-full bg-gray-50 border border-gray-200 text-xs font-semibold text-gray-600">
                  {rows.length} invoices
                </div>
              </div>
            </div>
          </div>
        </div>

        {rows.length === 0 ? (
          <div className="bg-white rounded-2xl shadow-lg shadow-gray-200/50 border border-gray-100 p-8 text-center">
            <p className="text-gray-600 font-semibold">
              No invoices saved yet.
            </p>
            <p className="text-sm text-gray-400 mt-2">
              Upload an invoice on Home page first.
            </p>
          </div>
        ) : (
          <div className="bg-white rounded-2xl shadow-lg shadow-gray-200/50 border border-gray-100 overflow-hidden">
            <div className="overflow-x-auto">
              <table className="w-full border-collapse">
                <thead>
                  <tr className="bg-indigo-600 text-white">
                    <th className="text-left text-[11px] font-bold uppercase tracking-wider py-3 px-4">
                      Invoice
                    </th>
                    <th className="text-left text-[11px] font-bold uppercase tracking-wider py-3 px-4">
                      Date
                    </th>
                    <th className="text-left text-[11px] font-bold uppercase tracking-wider py-3 px-4">
                      Client
                    </th>
                    <th className="text-right text-[11px] font-bold uppercase tracking-wider py-3 px-4">
                      Taxable
                    </th>
                    <th className="text-right text-[11px] font-bold uppercase tracking-wider py-3 px-4">
                      Total
                    </th>
                    <th className="text-right text-[11px] font-bold uppercase tracking-wider py-3 px-4">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((inv) => {
                    const busy = exportingId === inv._id;
                    return (
                      <tr key={inv._id} className="border-b border-gray-100">
                        <td className="py-4 px-4 text-sm text-gray-900 font-bold">
                          {inv.invoiceNumber}
                        </td>
                        <td className="py-4 px-4 text-sm text-gray-600">
                          {inv.invoiceDate}
                        </td>
                        <td className="py-4 px-4 text-sm text-gray-600">
                          {inv.clientName}
                        </td>
                        <td className="py-4 px-4 text-right text-sm text-gray-900 font-bold">
                          ₹ {formatINR(inv.taxableValue)}
                        </td>
                        <td className="py-4 px-4 text-right text-sm text-gray-900 font-extrabold">
                          ₹ {formatINR(inv.invoiceValue)}
                        </td>
                        <td className="py-4 px-4">
                          <div className="flex flex-wrap gap-2 justify-end">
                            <Button
                              variant="primary"
                              onClick={() => exportPDF(inv)}
                              iconLeft={Icons.pdf}
                              loading={busy && exportingType === "pdf"}
                            >
                              PDF
                            </Button>
                            <Button
                              variant="success"
                              onClick={() => exportExcel(inv)}
                              iconLeft={Icons.excel}
                              loading={busy && exportingType === "excel"}
                            >
                              Excel
                            </Button>
                            <Button
                              variant="warning"
                              onClick={() => exportXML(inv)}
                              iconLeft={Icons.xml}
                              loading={busy && exportingType === "xml"}
                            >
                              XML
                            </Button>
                          </div>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
